### ISSUE TITLE
API Key banned from Giphy

### ISSUE THREAD

**Issue by CHCMATT** [marcosmarp/GIFinderV2#1]
GIFinderV2 no longer works. When following the request (https://api.giphy.com/v1/gifs/search?api_key=dc6zaTOxFJmzC&q=cherry%20pie) through the console, looks like the API key is banned.

`{
      "data": [],
      "meta": {
        "status": 403,
        "msg": "BANNED",
        "response_id": ""
      }
    }`

https://i.imgur.com/wU6pZFB.png

**Comment by marcosmarp** [comment]
In just glad that someone is using this project lmao. I did it as an absolute beginner like a year ago. Will refresh the key tomorrow :)

**Comment by CHCMATT** [comment]
Hey @marcosmarp just wanted to let you know, it looks like the key still isn't working.

**Comment by marcosmarp** [comment]
solved!
